apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: graph-mail-mover
spec:
  externalSecretName: graph-mail-mover
  namespaceSelector:
    matchLabels:
      miak-it.com/graph-mail-mover: "true"
  externalSecretSpec:
    refreshPolicy: Periodic
    refreshInterval: 12h
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: graph-mail-mover
    target:
      name: graph-mail-mover
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: Opaque
        data:
          AZURE_TENANT_ID: "d6cda7f9-4db5-4558-917e-33132afc34fb"
          AZURE_CLIENT_ID: "{{ .client_id }}"
          AZURE_CLIENT_SECRET: "{{ .client_secret }}"
          AZURE_AUTHORITY_HOST: "https://login.microsoftonline.com"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: graph-onedrive-manager
spec:
  externalSecretName: graph-onedrive-manager
  namespaceSelector:
    matchLabels:
      miak-it.com/graph-onedrive-manager: "true"
  externalSecretSpec:
    refreshPolicy: Periodic
    refreshInterval: 12h
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: graph-onedrive-manager
    target:
      name: graph-onedrive-manager
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: Opaque
        data:
          AZURE_TENANT_ID: "d6cda7f9-4db5-4558-917e-33132afc34fb"
          AZURE_CLIENT_ID: "{{ .client_id }}"
          AZURE_CLIENT_SECRET: "{{ .client_secret }}"
          AZURE_AUTHORITY_HOST: "https://login.microsoftonline.com"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: graph-calendar-agent
spec:
  externalSecretName: graph-calendar-agent
  namespaceSelector:
    matchLabels:
      miak-it.com/graph-calendar-agent: "true"
  externalSecretSpec:
    refreshPolicy: Periodic
    refreshInterval: 12h
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: graph-calendar-agent
    target:
      name: graph-calendar-agent
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: Opaque
        data:
          AZURE_TENANT_ID: "d6cda7f9-4db5-4558-917e-33132afc34fb"
          AZURE_CLIENT_ID: "{{ .client_id }}"
          AZURE_CLIENT_SECRET: "{{ .client_secret }}"
          AZURE_AUTHORITY_HOST: "https://login.microsoftonline.com"
