apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miak-website
  namespace: miak-website
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: miak-website
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: miak-website
        property: SECRET_KEY_BASE
    - secretKey: MAKE_WEBHOOK_API_KEY
      remoteRef:
        key: miak-website
        property: MAKE_WEBHOOK_API_KEY
    - secretKey: TURNSTILE_SECRET_KEY
      remoteRef:
        key: miak-website
        property: TURNSTILE_SECRET_KEY
    - secretKey: TURNSTILE_SITE_KEY
      remoteRef:
        key: miak-website
        property: TURNSTILE_SITE_KEY
