apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill
  namespace: windmill
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: windmill
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        SERVICE_USER_POSTGRES: "{{ .SERVICE_USER_POSTGRES }}"
        SERVICE_PASSWORD_POSTGRES: "{{ .SERVICE_PASSWORD_POSTGRES }}"
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        DATABASE_URL: "postgres://{{ .SERVICE_USER_POSTGRES }}:{{ .SERVICE_PASSWORD_POSTGRES }}@postgres.database.svc.cluster.local:5432/windmill"
  data:
    - secretKey: SERVICE_USER_POSTGRES
      remoteRef:
        key: windmill
        property: SERVICE_USER_POSTGRES
    - secretKey: SERVICE_PASSWORD_POSTGRES
      remoteRef:
        key: windmill
        property: SERVICE_PASSWORD_POSTGRES
    - secretKey: POSTGRES_DB
      remoteRef:
        key: windmill
        property: POSTGRES_DB
