apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kids-prep
  namespace: kids-prep
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: kids-prep
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: kids-prep
        property: SECRET_KEY_BASE
    - secretKey: OPENBAO_ROLE_ID
      remoteRef:
        key: kids-prep
        property: OPENBAO_ROLE_ID
    - secretKey: OPENBAO_SECRET_ID
      remoteRef:
        key: kids-prep
        property: OPENBAO_SECRET_ID
