apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: n8n
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: n8n
    creationPolicy: Owner
  data:
    - secretKey: SERVICE_USER_POSTGRES
      remoteRef:
        key: n8n
        property: SERVICE_USER_POSTGRES
    - secretKey: SERVICE_PASSWORD_POSTGRES
      remoteRef:
        key: n8n
        property: SERVICE_PASSWORD_POSTGRES
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: N8N_RUNNERS_AUTH_TOKEN
      remoteRef:
        key: n8n
        property: N8N_RUNNERS_AUTH_TOKEN
    - secretKey: N8N_SKIP_AUTH_ON_OAUTH_CALLBACK
      remoteRef:
        key: n8n
        property: N8N_SKIP_AUTH_ON_OAUTH_CALLBACK
    - secretKey: VALKEY_PASSWORD
      remoteRef:
        key: platform/valkey
        property: VALKEY_PASSWORD
