apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-demo
  namespace: secret-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: openbao-demo
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: demo/app
        property: username
    - secretKey: password
      remoteRef:
        key: demo/app
        property: password

